CREATE TABLE USER (
  ID          BIGINT          NOT NULL   AUTO_INCREMENT,
  PHONE       VARCHAR(255)    NULL,
  ADDITIONAL  VARCHAR(4000)   NULL,

  PRIMARY KEY (ID)
);

CREATE TABLE USER_CREDENTIALS (
  ID          BIGINT          NOT NULL AUTO_INCREMENT,
  LOGIN       VARCHAR(255)    NOT NULL,
  PASSWORD    VARCHAR(255)    NOT NULL,
  ROLE        VARCHAR(255)    NOT NULL,
  FK_USER_ID  BIGINT          NULL,

  PRIMARY KEY (ID),

  CONSTRAINT USERNAME_UNIQUE    UNIQUE (LOGIN),
  CONSTRAINT FK_USER_ID_UNIQUE  UNIQUE (FK_USER_ID),
  CONSTRAINT FK_USER_CREDENTIALS_USER_ID
    FOREIGN KEY (FK_USER_ID)
    REFERENCES USER (ID)
);

CREATE TABLE CUSTOMER (
  FNAME       VARCHAR(255)    NOT NULL,
  LNAME       VARCHAR(255)    NOT NULL,
  ID          BIGINT          NOT NULL,

  PRIMARY KEY (ID),

  CONSTRAINT FK_CUSTOMER_USER_ID
    FOREIGN KEY (ID)
    REFERENCES USER (ID)
);

CREATE TABLE EXECUTOR (
  ID          BIGINT          NOT NULL,

  PRIMARY KEY (ID),

  CONSTRAINT FK_EXECUTOR_USER_ID
    FOREIGN KEY (ID)
    REFERENCES USER (ID)
);
