server:
  port: 9092

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/profit_print_db
    username: profit-print
    password: profit-pass

security:
  ignored: /**

web:
  security:
    enabled: true
    jwt:
      signingKey: profitPrintSecret
      expirationTime: 30